// <auto-generated />
namespace MD.GigHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class overrideconditionforgenres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(overrideconditionforgenres));
        
        string IMigrationMetadata.Id
        {
            get { return "202102121548103_overrideconditionforgenres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
